2017-01-01T07:00:16.643Z - error: uncaughtException: DatabaseUtil is not defined date=Sun Jan 01 2017 08:00:16 GMT+0100 (W. Europe Standard Time), pid=13248, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=114429952, heapTotal=95813632, heapUsed=54097944, loadavg=[0, 0, 0], uptime=475985.1326021, trace=[column=4, file=C:/Users/phili/Documents/GitHub/venos/server.js, function=_loop, line=91, method=null, native=false, column=37, file=C:/Users/phili/Documents/GitHub/venos/server.js, function=null, line=86, method=null, native=false, column=9, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=, line=105, method=null, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=IncomingForm.emit, line=185, method=emit, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=IncomingForm._maybeEnd, line=553, method=_maybeEnd, native=false, column=12, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=null, line=230, method=null, native=false, column=5, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js, function=, line=70, method=null, native=false, column=16, file=events.js, function=WriteStream.g, line=291, method=g, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false], stack=[ReferenceError: DatabaseUtil is not defined,     at _loop (C:/Users/phili/Documents/GitHub/venos/server.js:91:4),     at C:/Users/phili/Documents/GitHub/venos/server.js:86:37,     at IncomingForm.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:105:9),     at emitNone (events.js:86:13),     at IncomingForm.emit (events.js:185:7),     at IncomingForm._maybeEnd (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:553:8),     at C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:230:12,     at WriteStream.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js:70:5),     at WriteStream.g (events.js:291:16),     at emitNone (events.js:91:20)]
2017-01-01T07:01:30.256Z - error: uncaughtException: DatabaseUtil is not defined date=Sun Jan 01 2017 08:01:30 GMT+0100 (W. Europe Standard Time), pid=12032, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=113504256, heapTotal=94765056, heapUsed=57444752, loadavg=[0, 0, 0], uptime=476058.7475095, trace=[column=4, file=C:/Users/phili/Documents/GitHub/venos/server.js, function=_loop, line=91, method=null, native=false, column=37, file=C:/Users/phili/Documents/GitHub/venos/server.js, function=null, line=86, method=null, native=false, column=9, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=, line=105, method=null, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=IncomingForm.emit, line=185, method=emit, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=IncomingForm._maybeEnd, line=553, method=_maybeEnd, native=false, column=12, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=null, line=230, method=null, native=false, column=5, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js, function=, line=70, method=null, native=false, column=16, file=events.js, function=WriteStream.g, line=291, method=g, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false], stack=[ReferenceError: DatabaseUtil is not defined,     at _loop (C:/Users/phili/Documents/GitHub/venos/server.js:91:4),     at C:/Users/phili/Documents/GitHub/venos/server.js:86:37,     at IncomingForm.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:105:9),     at emitNone (events.js:86:13),     at IncomingForm.emit (events.js:185:7),     at IncomingForm._maybeEnd (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:553:8),     at C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:230:12,     at WriteStream.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js:70:5),     at WriteStream.g (events.js:291:16),     at emitNone (events.js:91:20)]
2017-01-01T07:03:31.072Z - error: uncaughtException: _database4.default.createFile is not a function date=Sun Jan 01 2017 08:03:31 GMT+0100 (W. Europe Standard Time), pid=17788, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=113700864, heapTotal=94765056, heapUsed=53614336, loadavg=[0, 0, 0], uptime=476179.564802, trace=[column=17, file=C:/Users/phili/Documents/GitHub/venos/server.js, function=_loop, line=92, method=null, native=false, column=37, file=C:/Users/phili/Documents/GitHub/venos/server.js, function=null, line=87, method=null, native=false, column=9, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=, line=105, method=null, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=IncomingForm.emit, line=185, method=emit, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=IncomingForm._maybeEnd, line=553, method=_maybeEnd, native=false, column=12, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=null, line=230, method=null, native=false, column=5, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js, function=, line=70, method=null, native=false, column=16, file=events.js, function=WriteStream.g, line=291, method=g, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false], stack=[TypeError: _database4.default.createFile is not a function,     at _loop (C:/Users/phili/Documents/GitHub/venos/server.js:92:17),     at C:/Users/phili/Documents/GitHub/venos/server.js:87:37,     at IncomingForm.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:105:9),     at emitNone (events.js:86:13),     at IncomingForm.emit (events.js:185:7),     at IncomingForm._maybeEnd (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:553:8),     at C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:230:12,     at WriteStream.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js:70:5),     at WriteStream.g (events.js:291:16),     at emitNone (events.js:91:20)]
2017-01-01T07:04:45.911Z - error: uncaughtException: _database4.default.addFileToHub is not a function date=Sun Jan 01 2017 08:04:45 GMT+0100 (W. Europe Standard Time), pid=8260, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=114114560, heapTotal=95813632, heapUsed=53599200, loadavg=[0, 0, 0], uptime=476254.4029501, trace=[column=17, file=C:/Users/phili/Documents/GitHub/venos/server.js, function=_loop, line=92, method=null, native=false, column=37, file=C:/Users/phili/Documents/GitHub/venos/server.js, function=null, line=87, method=null, native=false, column=9, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=, line=105, method=null, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=IncomingForm.emit, line=185, method=emit, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=IncomingForm._maybeEnd, line=553, method=_maybeEnd, native=false, column=12, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=null, line=230, method=null, native=false, column=5, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js, function=, line=70, method=null, native=false, column=16, file=events.js, function=WriteStream.g, line=291, method=g, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false], stack=[TypeError: _database4.default.addFileToHub is not a function,     at _loop (C:/Users/phili/Documents/GitHub/venos/server.js:92:17),     at C:/Users/phili/Documents/GitHub/venos/server.js:87:37,     at IncomingForm.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:105:9),     at emitNone (events.js:86:13),     at IncomingForm.emit (events.js:185:7),     at IncomingForm._maybeEnd (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:553:8),     at C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:230:12,     at WriteStream.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js:70:5),     at WriteStream.g (events.js:291:16),     at emitNone (events.js:91:20)]
2017-01-01T07:13:32.111Z - error: uncaughtException: _database2.default.addFileToHub is not a function date=Sun Jan 01 2017 08:13:32 GMT+0100 (W. Europe Standard Time), pid=14804, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=55349248, heapTotal=37834752, heapUsed=30416592, loadavg=[0, 0, 0], uptime=476780.6093084, trace=[column=19, file=C:\Users\phili\Documents\GitHub\venos\server.js, function=_loop, line=92, method=null, native=false, column=37, file=C:\Users\phili\Documents\GitHub\venos\server.js, function=null, line=87, method=null, native=false, column=9, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=, line=105, method=null, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=IncomingForm.emit, line=185, method=emit, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=IncomingForm._maybeEnd, line=553, method=_maybeEnd, native=false, column=12, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js, function=null, line=230, method=null, native=false, column=5, file=C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js, function=, line=70, method=null, native=false, column=16, file=events.js, function=WriteStream.g, line=291, method=g, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false], stack=[TypeError: _database2.default.addFileToHub is not a function,     at _loop (C:\Users\phili\Documents\GitHub\venos\server.js:92:19),     at C:\Users\phili\Documents\GitHub\venos\server.js:87:37,     at IncomingForm.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:105:9),     at emitNone (events.js:86:13),     at IncomingForm.emit (events.js:185:7),     at IncomingForm._maybeEnd (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:553:8),     at C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\incoming_form.js:230:12,     at WriteStream.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\formidable\lib\file.js:70:5),     at WriteStream.g (events.js:291:16),     at emitNone (events.js:91:20)]
2017-01-01T07:14:34.299Z - error: uncaughtException: Cannot find module 'C:\Users\phili\Documents\GitHub\venos\service.json' date=Sun Jan 01 2017 08:14:34 GMT+0100 (W. Europe Standard Time), pid=14008, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=57036800, heapTotal=36786176, heapUsed=30292824, loadavg=[0, 0, 0], uptime=476842.7973227, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=455, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=403, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=483, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=14, file=C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js, function=Auth.getAuthClient, line=53, method=getAuthClient, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js, function=Auth.getToken, line=156, method=getToken, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js, function=Auth.authorizeRequest, line=20, method=authorizeRequest, native=false, column=19, file=C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js, function=Upload.makeRequest, line=267, method=makeRequest, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js, function=Upload.createURI, line=126, method=createURI, native=false, column=12, file=C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js, function=, line=76, method=null, native=false], stack=[Error: Cannot find module 'C:\Users\phili\Documents\GitHub\venos\service.json',     at Function.Module._resolveFilename (module.js:455:15),     at Function.Module._load (module.js:403:25),     at Module.require (module.js:483:17),     at require (internal/module.js:20:19),     at Auth.getAuthClient (C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js:53:14),     at Auth.getToken (C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js:156:8),     at Auth.authorizeRequest (C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js:20:8),     at Upload.makeRequest (C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js:267:19),     at Upload.createURI (C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js:126:8),     at Upload.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js:76:12)]
2017-01-01T07:26:22.479Z - error: uncaughtException: Cannot find module 'C:\Users\phili\Documents\GitHub\venos\service.json' date=Sun Jan 01 2017 08:26:22 GMT+0100 (W. Europe Standard Time), pid=14008, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=56700928, heapTotal=37834752, heapUsed=30673728, loadavg=[0, 0, 0], uptime=477550.9789626, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=455, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=403, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=483, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=14, file=C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js, function=Auth.getAuthClient, line=53, method=getAuthClient, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js, function=Auth.getToken, line=156, method=getToken, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js, function=Auth.authorizeRequest, line=20, method=authorizeRequest, native=false, column=19, file=C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js, function=Upload.makeRequest, line=267, method=makeRequest, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js, function=Upload.createURI, line=126, method=createURI, native=false, column=12, file=C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js, function=, line=76, method=null, native=false], stack=[Error: Cannot find module 'C:\Users\phili\Documents\GitHub\venos\service.json',     at Function.Module._resolveFilename (module.js:455:15),     at Function.Module._load (module.js:403:25),     at Module.require (module.js:483:17),     at require (internal/module.js:20:19),     at Auth.getAuthClient (C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js:53:14),     at Auth.getToken (C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js:156:8),     at Auth.authorizeRequest (C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js:20:8),     at Upload.makeRequest (C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js:267:19),     at Upload.createURI (C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js:126:8),     at Upload.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js:76:12)]
2017-01-01T07:54:30.723Z - error: uncaughtException: Cannot find module 'C:\Users\phili\Documents\GitHub\venos\service.json' date=Sun Jan 01 2017 08:54:30 GMT+0100 (W. Europe Standard Time), pid=6240, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=85291008, heapTotal=69341184, heapUsed=45250912, loadavg=[0, 0, 0], uptime=479239.222678, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=455, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=403, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=483, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=14, file=C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js, function=Auth.getAuthClient, line=53, method=getAuthClient, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js, function=Auth.getToken, line=156, method=getToken, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js, function=Auth.authorizeRequest, line=20, method=authorizeRequest, native=false, column=19, file=C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js, function=Upload.makeRequest, line=267, method=makeRequest, native=false, column=8, file=C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js, function=Upload.createURI, line=126, method=createURI, native=false, column=12, file=C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js, function=, line=76, method=null, native=false], stack=[Error: Cannot find module 'C:\Users\phili\Documents\GitHub\venos\service.json',     at Function.Module._resolveFilename (module.js:455:15),     at Function.Module._load (module.js:403:25),     at Module.require (module.js:483:17),     at require (internal/module.js:20:19),     at Auth.getAuthClient (C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js:53:14),     at Auth.getToken (C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js:156:8),     at Auth.authorizeRequest (C:\Users\phili\Documents\GitHub\venos\node_modules\google-auto-auth\index.js:20:8),     at Upload.makeRequest (C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js:267:19),     at Upload.createURI (C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js:126:8),     at Upload.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\gcs-resumable-upload\index.js:76:12)]
2017-01-01T07:55:31.944Z - error: uncaughtException: console.err is not a function date=Sun Jan 01 2017 08:55:31 GMT+0100 (W. Europe Standard Time), pid=12344, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=57729024, heapTotal=38883328, heapUsed=31701000, loadavg=[0, 0, 0], uptime=479300.4400617, trace=[column=33, file=C:\Users\phili\Documents\GitHub\venos\server.js, function=null, line=118, method=null, native=false, column=9, file=C:\Users\phili\Documents\GitHub\venos\node_modules\@google-cloud\storage\src\bucket.js, function=, line=1218, method=null, native=false, column=20, file=events.js, function=emitOne, line=101, method=null, native=false, column=7, file=events.js, function=Pumpify.emit, line=188, method=emit, native=false, column=15, file=C:\Users\phili\Documents\GitHub\venos\node_modules\duplexify\index.js, function=Pumpify.Duplexify._destroy, line=184, method=Duplexify._destroy, native=false, column=10, file=C:\Users\phili\Documents\GitHub\venos\node_modules\duplexify\index.js, function=null, line=175, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=67, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[TypeError: console.err is not a function,     at C:\Users\phili\Documents\GitHub\venos\server.js:118:33,     at Pumpify.<anonymous> (C:\Users\phili\Documents\GitHub\venos\node_modules\@google-cloud\storage\src\bucket.js:1218:9),     at emitOne (events.js:101:20),     at Pumpify.emit (events.js:188:7),     at Pumpify.Duplexify._destroy (C:\Users\phili\Documents\GitHub\venos\node_modules\duplexify\index.js:184:15),     at C:\Users\phili\Documents\GitHub\venos\node_modules\duplexify\index.js:175:10,     at _combinedTickCallback (internal/process/next_tick.js:67:7),     at process._tickCallback (internal/process/next_tick.js:98:9)]
2017-01-01T08:20:34.730Z - error: uncaughtException: _database3.Firebase.storage is not a function date=Sun Jan 01 2017 09:20:34 GMT+0100 (W. Europe Standard Time), pid=7076, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=40189952, heapTotal=33591296, heapUsed=19085528, loadavg=[0, 0, 0], uptime=480803.2271102, trace=[column=24, file=C:\Users\phili\Documents\GitHub\venos\server.js, function=, line=31, method=null, native=false, column=32, file=module.js, function=Module._compile, line=556, method=_compile, native=false, column=13, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=babelWatchLoader, line=50, method=null, native=false, column=7, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=Object.require.extensions.(anonymous function) [as .js], line=61, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=473, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=432, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=424, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain, line=590, method=Module.runMain, native=false, column=21, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=process.on, line=108, method=on, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false], stack=[TypeError: _database3.Firebase.storage is not a function,     at Object.<anonymous> (C:\Users\phili\Documents\GitHub\venos\server.js:31:24),     at Module._compile (module.js:556:32),     at babelWatchLoader (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:50:13),     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:61:7),     at Module.load (module.js:473:32),     at tryModuleLoad (module.js:432:12),     at Function.Module._load (module.js:424:3),     at Function.Module.runMain (module.js:590:10),     at process.on (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:108:21),     at emitTwo (events.js:106:13)]
2017-01-01T08:24:42.583Z - error: uncaughtException: _shared.Firebase.storage is not a function date=Sun Jan 01 2017 09:24:42 GMT+0100 (W. Europe Standard Time), pid=8000, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=40341504, heapTotal=33591296, heapUsed=19089328, loadavg=[0, 0, 0], uptime=481051.0814361, trace=[column=24, file=C:\Users\phili\Documents\GitHub\venos\server.js, function=, line=31, method=null, native=false, column=32, file=module.js, function=Module._compile, line=556, method=_compile, native=false, column=13, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=babelWatchLoader, line=50, method=null, native=false, column=7, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=Object.require.extensions.(anonymous function) [as .js], line=61, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=473, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=432, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=424, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain, line=590, method=Module.runMain, native=false, column=21, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=process.on, line=108, method=on, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false], stack=[TypeError: _shared.Firebase.storage is not a function,     at Object.<anonymous> (C:\Users\phili\Documents\GitHub\venos\server.js:31:24),     at Module._compile (module.js:556:32),     at babelWatchLoader (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:50:13),     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:61:7),     at Module.load (module.js:473:32),     at tryModuleLoad (module.js:432:12),     at Function.Module._load (module.js:424:3),     at Function.Module.runMain (module.js:590:10),     at process.on (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:108:21),     at emitTwo (events.js:106:13)]
2017-01-01T08:24:55.706Z - error: uncaughtException: _shared.Firebase.storage is not a function date=Sun Jan 01 2017 09:24:55 GMT+0100 (W. Europe Standard Time), pid=18096, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=40497152, heapTotal=33591296, heapUsed=19122992, loadavg=[0, 0, 0], uptime=481064.2037349, trace=[column=24, file=C:\Users\phili\Documents\GitHub\venos\server.js, function=, line=31, method=null, native=false, column=32, file=module.js, function=Module._compile, line=556, method=_compile, native=false, column=13, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=babelWatchLoader, line=50, method=null, native=false, column=7, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=Object.require.extensions.(anonymous function) [as .js], line=61, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=473, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=432, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=424, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain, line=590, method=Module.runMain, native=false, column=21, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=process.on, line=108, method=on, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false], stack=[TypeError: _shared.Firebase.storage is not a function,     at Object.<anonymous> (C:\Users\phili\Documents\GitHub\venos\server.js:31:24),     at Module._compile (module.js:556:32),     at babelWatchLoader (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:50:13),     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:61:7),     at Module.load (module.js:473:32),     at tryModuleLoad (module.js:432:12),     at Function.Module._load (module.js:424:3),     at Function.Module.runMain (module.js:590:10),     at process.on (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:108:21),     at emitTwo (events.js:106:13)]
2017-01-01T10:44:19.747Z - error: uncaughtException: Cannot read property 'bucket' of undefined date=Sun Jan 01 2017 11:44:19 GMT+0100 (W. Europe Standard Time), pid=16308, uid=null, gid=null, cwd=C:\Users\phili\Documents\GitHub\venos, execPath=C:\Program Files\nodejs\node.exe, version=v6.7.0, argv=[node, C:\Users\phili\Documents\GitHub\venos\server.js], rss=78024704, heapTotal=65146880, heapUsed=41121016, loadavg=[0, 0, 0], uptime=489428.2442673, trace=[column=14, file=C:\Users\phili\Documents\GitHub\venos\server.js, function=, line=59, method=null, native=false, column=32, file=module.js, function=Module._compile, line=556, method=_compile, native=false, column=13, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=babelWatchLoader, line=50, method=null, native=false, column=7, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=Object.require.extensions.(anonymous function) [as .js], line=61, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=473, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=432, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=424, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain, line=590, method=Module.runMain, native=false, column=21, file=C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js, function=process.on, line=108, method=on, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false], stack=[TypeError: Cannot read property 'bucket' of undefined,     at Object.<anonymous> (C:\Users\phili\Documents\GitHub\venos\server.js:59:14),     at Module._compile (module.js:556:32),     at babelWatchLoader (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:50:13),     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:61:7),     at Module.load (module.js:473:32),     at tryModuleLoad (module.js:432:12),     at Function.Module._load (module.js:424:3),     at Function.Module.runMain (module.js:590:10),     at process.on (C:\Users\phili\Documents\GitHub\venos\node_modules\babel-watch\runner.js:108:21),     at emitTwo (events.js:106:13)]
